### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by ghost** [OpenRoberta/robertalab-ev3dev#23]
"Fehler im EV3 
AttributeError
'NoneType'  object has no attributes

Press any key"

This showed up on the screen when trying to run a simple motor program.
How to fix it?

I am running this on the latest version of ev3dev

**Comment by ensonic** [comment]
See #21 - you probably have used some blocks that use motors/sensors which are not connected on the physical robot. This is going to be improved with the new openroberta release (2.0 is almost out).
