### ISSUE TITLE
Infinite wait loop cannot be interrupted on EV3

### ISSUE THREAD

**Issue by drigz** [OpenRoberta/robertalab-ev3dev#25]
I sent the following program to the EV3:

![image](https://cloud.githubusercontent.com/assets/632207/20316622/e09477cc-ab62-11e6-9efc-6a827d6d3a16.png)

We couldn't interrupt the program by holding center+down, nor by holding power. We had to remove the battery pack.

**Comment by ensonic** [comment]
This must have been something else. I tried the above example multiple times and could always kill it. One explanation could be that switching the framebuffer console back to the one running brickman failed. Unfortunately to verify I'd need to be logged it :/
