### ISSUE TITLE
EV3 not working after OpenRoberta upgrade

### ISSUE THREAD

**Issue by JimZam** [OpenRoberta/robertalab-ev3dev#26]
Good morning. After the last OpenRoberta update all I get is a white screen when trying to run any program from the openroberta web or offline server. I can access via ssh.
Thank you and regards

**Comment by ensonic** [comment]
Server update or local package update? If you can ssh in, then this could help:
https://github.com/OpenRoberta/robertalab-ev3dev#logging
Put the last few lines on a gist.github.com and share it here, if that is okay with you.

**Comment by JimZam** [comment]
I upgraded openrobertalab in the EV3, will post the status this evening (I'm in Spain :-) )
Thank you

**Comment by JimZam** [comment]
Ok, it seems to work now. Something to do with the existing NEPOprog.py file:

Nov 27 16:52:50 ev3dev openrobertalab[386]: PermissionError: [Errno 13] Permission denied: '/home/robot/NEPOprog.py'

I deleted it, ran the program from the web browser and everything was fine.

By the way, if I try to run "python NEPOprog.py" from the command line it keeps on failing (it seems it would be solved in this update according to my last question)

robot@ev3dev:/home/robot# python NEPOprog.py
Traceback (most recent call last):
  File "NEPOprog.py", line 3, in <module>
    from roberta.ev3 import Hal
ImportError: No module named roberta.ev3

Thank you so much for your help and for OpenRoberta

**Comment by ensonic** [comment]
Not being able to run the programs from the brick (e.g. the file browser) is fixed with the new release - when upgrading from python2 to python3, I forgot to update the first line in the script :/
The stored programs unfortunately will only work for as long as the python libraries don't change in an incompatible way.

**Comment by ensonic** [comment]
I'll check what happens if a program cannot be overwritten and how I can gracefully handle this.

**Comment by ensonic** [comment]
I am already catching the error, but only logging it. The program would run, but not be stored. I don't see a good way of solving this though. 
At some point I can report back to the server that the program already existed and could not be overwritten (see #20).
