### ISSUE TITLE
Robot doesn't tell you when the server has the pairing code

### ISSUE THREAD

**Issue by drigz** [OpenRoberta/robertalab-ev3dev#27]
When the robot generates the pairing code, it shows it on the screen. If the WiFi is unreliable, it may not yet be registered on the server, so when you try to enter it in the Lab you get an error.

If would be nice if we could have a string on the screen that starts eg "Connecting..." then changes to "Connected" when it's ready. This would save you repeated entering the code again and again until the server has it.

**Comment by ensonic** [comment]
Yep, I have some more info in #30, but it is unfortunately quite tricky :/
