### ISSUE TITLE
Robot shows code for a short period then it disappears

### ISSUE THREAD

**Issue by drigz** [OpenRoberta/robertalab-ev3dev#28]
1. On bad WiFi, try to connect to the OpenRoberta Lab.
2. Robot shows code for a few seconds.
3. Robot stops showing code and returns to "Connect" screen.
4. You have to keep selecting "Connect" until the code stays on the screen long enough to connect.

Could this be fixed by retrying with the same code until we connect successfully?

**Comment by ensonic** [comment]
I have a global flag to keep using the same code, but the server code was changed to not accept the same code for reconnecting. I'll need to recheck if this got fixed.

Ideally we find a way also to make the whole communication more robust to temporary loss of connection.

**Comment by DJuego** [comment]
Yes. Yes. I can confirm this issue. I had the same problem in a workshop (10 EV3 bricks) yesterday with a local wifi dedicated router.

Also I had other problems. 

b) Sometimes the code does not get connected at the first shot.
c) a message box: "The EV3 does not expect an order of starting" or so. (when the user tries to launch his/her program)

DJuego

**Comment by ensonic** [comment]
A 2nd issue seems that the server side assumes certain timeout and if they are not meet unregisters the robot. I need to collect evidence, but what I saw is that in the web ui, the "EV3" string turned from colors to black and selecting 'INFO' from the menu reported the robot to be in state: disconnected.
