### ISSUE TITLE
D-Bus service should not give a new code each time you connect.

### ISSUE THREAD

**Issue by dlech** [OpenRoberta/robertalab-ev3dev#3]
The web UI remembers the last code used. So, if you should become disconnected, the dbus service should provide the same code - at least for each D-Bus client. This way you don't have to type in a new code so often.

**Comment by ensonic** [comment]
Good idea, I'll try to reuse the same code as long as the service runs.

**Comment by ensonic** [comment]
The git version of the server is not keeping the code in the entry box anymore. Will discuss with the other devs. What most of us seem to do is to run a local server and copy'n'paste the token from the server log :)
