### ISSUE TITLE
Trouble with motor port on speed?

### ISSUE THREAD

**Issue by DJuego** [OpenRoberta/robertalab-ev3dev#32]
I have the next code:
[http://imgur.com/a/jBPtd](http://imgur.com/a/jBPtd)

openrobertalab translate to the next python code:
[http://paste.ofcode.org/3zkwC5v33ZRHdWTm7AJRdC](http://paste.ofcode.org/3zkwC5v33ZRHdWTm7AJRdC)

The EV3 behaviour is not expected. I expected:

When the touch sensor is pressed, the medium motor stops. However the program does not finish.
In any moment, when it the console up button is pressed, the program finish. 

The EV3 behaviour i got:

The medium motor turn on a second and stop.
The touch sensor is not stop the medium motor.
The console up button is not stop the program.
Blank screen
I have to reboot the EV3 with ENTER+LEFT+BACK

The problem happen with motor B and C too. 

My configuration is:

Medium motor (A)
Big motor (B)
Big motor (C)

Touch sensor (1)
Gyroscope sensor (2)
Light/colour sensor (3)
Ultrasonic sensor (4)

I am working with the 2017-01-25 fully updated. (2017-01-28)

**Comment by DJuego** [comment]
Ok i have re-tried it without the button stuff (probably there are a problem with the button due to kernel recently updated: [https://github.com/ev3dev/ev3dev/issues/820](https://github.com/ev3dev/ev3dev/issues/820)

I have the same code but with this modification: __**Repeat until (get distance ultrasonic port 4) <= 5)_**

The motor A turn on and stop when i press the touch sensor ( expected behaviour). Good

HOWEVER i have discovered when the program finish (exit of the loop) the EV3 frozen. :-(
I have to reboot the EV3.

**Comment by ensonic** [comment]
This seems to be all related to the keyboard changes. This way openrobertalab recognizes a cancel key press and restarts. I'll send a pull request for the python lib.

**Comment by ensonic** [comment]
Fixed via rhempel/ev3dev-lang-python#286
