### ISSUE TITLE
robertalab-ev3dev hangs when motor stalls

### ISSUE THREAD

**Issue by bidaian** [OpenRoberta/robertalab-ev3dev#33]
Hi,

I'm using using the latest snapshot-ev3dev-jessie-ev3-generic-2017-02-08.img on EV3, with the SPIK3R robot.
If a motor is blocked (stalled) then robertalab hangs forever.

We are trying to find the range of movement, but each time it hangs. Is there a way not to have the connector hang forever?

**Comment by ensonic** [comment]
Can you attach your program (export the xml from the open-roberta lab) or attach a screenshot?

**Comment by bidaian** [comment]
[nepoprog.zip](https://github.com/OpenRoberta/robertalab-ev3dev/files/767769/nepoprog.zip)
 This is it. The robot is [this one](https://www.lego.com/en-us/mindstorms/build-a-robot/spik3r) and we are trying to move the tail. Whenever the tail goes "out of range" the whole robot hangs and we have to restart it. The motor stays blocked, I mean, not floating. You can ssh into the robot. Now we're back using the stable ev3dev-jessie-ev3 but the problem persists.

I see many:

```
while (m.state):
                self.busyWait()
```
Could the problem be there? It seems to have the same behaviour for all states. Maybe when 'stalled' the motor could be stopped.
