### ISSUE TITLE
Indentation problems in the generated python code 

### ISSUE THREAD

**Issue by DJuego** [OpenRoberta/robertalab-ev3dev#39]
There are problems with indentation. For any unknown reason the programs are "corrupted"... 
It is very problematic. :-(

This sample has been generated from a bigger "corrupted" program. The "corruption" remains...

http://i.imgur.com/gfoMj5W.png

This code is generated:

http://i.imgur.com/EWNWNk6.png

I attach the XML file.

[NEPOprog.zip](https://github.com/OpenRoberta/robertalab-ev3dev/files/980833/NEPOprog.zip)

I am working with a open roberta server local (2.2.3).

**Comment by ensonic** [comment]
This is a blockly issue. If you move the function below the start block the generated code is correct. We've updated blockly in git and this will be fixed with the next release of the server.
