### ISSUE TITLE
"You are trying to connect a robot of a different type [...]"

### ISSUE THREAD

**Issue by DJuego** [OpenRoberta/robertalab-ev3dev#42]
Hi. I am working in Windows 10 x64 with a openroberta local server (2.2.4). 

Recently I have discovered any EV3 fails in connecting. I have test  with the Open Roberta connector (updated in 2017.06.03).

I get:
_You are trying to connect a robot of a different type as selected in the menu. 
Please switch the robot type in the robot's menu and try to connect again!_

However another bricks connect without troubles.

I have any research. 

- openroberta local server (2.2.4) 
- In this test the connector openroberta-ev3dev is closed at the end of April, 2017.

I have two EV3 bricks,  I am using USB cable.

1) I load the openroberta page. I select Ev3->EV3dev
2) I try to connect the first EV3. The code is 27Z92WHQ.
3) The connection is successfully. 
4) I disconnect the first EV3.
5) I reload the openroberta page.  I select Ev3->EV3dev
6) I try to connect the second EV3.  The code is HKQGZN3T.
7) The connection **fails**.

_You are trying to connect a robot of a different type as selected in the menu. 
Please switch the robot type in the robot's menu and try to connect again!_

Here the openroberta server log:
[LINK](https://paste.ofcode.org/ZrLKkkSDM4XrurG9Jfk68S)

I think It is remarkable the text: 

` token HKQGZN3T belongs to a robot of type ev3, client is set to ev3dev`

There is at least one difference between the 'good' EV3 and the 'bad' units. The 'problematic' EV3s had/have a Netgear wifi dongle. The wifi was enabled and it worked perfectly but, casually, we don´t work with Open Roberta with those units... For that reason I had not detected this problem before.

However the wifi is disabled now. No dongle. The problem persists. No idea it it is related. I am going to test more deeply this way... but i need time.

DJuego

**Comment by afgym-baeu** [comment]
I´ve had the same problem when I changed the hostname (using ev3dev-config on ssh console) to another value than "ev3dev". Still wondering how two robots communicate to each other if I am not allowed to change the hostname ...

**Comment by DJuego** [comment]
Yes, yes, yes! @MaikBaeumer.  Indeed!! That must be! In order to activate the wifi i change the hostname too. I had not noticed that 'pattern'. 👍  it is very probable the problem is not wifi but the hostname!!.

DJuego

Yes! I can confirm it now. I change to the old hostname 'ev3dev' and it works!

**Comment by ensonic** [comment]
Lets track this via #43.
