### ISSUE TITLE
server error when using message blocks

### ISSUE THREAD

**Issue by afgym-baeu** [OpenRoberta/robertalab-ev3dev#44]
The lab (lab.open-roberta.org, release 2.2.5, ev3dev) shows a "Attention - Server error" popup when starting a program that contains a message block, even a simple `wait for connection`. The gui switches to a new project and all unsaved programming is lost.

**Comment by afgym-baeu** [comment]
This is the server's error log:

`2017-06-13 21:21:07,526 [qtp28241199-15] session-id=[1] user-id=[-1] robot-name=[ev3dev] ERROR d.f.i.r.j.r.all.ClientProgram - Exception. Error ticket: E-1
java.lang.ClassCastException: de.fhg.iais.roberta.syntax.check.hardware.RobotProgramCheckVisitor cannot be cast to de.fhg.iais.roberta.visitor.actor.AstActorCommunicationVisitor
	at de.fhg.iais.roberta.syntax.action.communication.BluetoothWaitForConnectionAction.accept(BluetoothWaitForConnectionAction.java:40) ~[OpenRobertaRobot-2.2.5-SNAPSHOT.jar:na]`

I'm wondering if this is ev3dev specific or should be reported as an issue to the openrobertalab repository!?

**Comment by afgym-baeu** [comment]
Just discovered same exception when using leJOS EV3.

**Comment by ensonic** [comment]
Could you please file server side bug on the robertalab? This saves me quite a bit of time copying them over.

**Comment by afgym-baeu** [comment]
Done. It's [url](https://github.com/OpenRoberta/robertalab/issues/529)
