### ISSUE TITLE
Use espeak oder play a ".wav" file

### ISSUE THREAD

**Issue by peacepro** [OpenRoberta/robertalab-ev3dev#48]
Hi,
i have installed the ev3dev on my brick and use robertalab to program my robot. 
Is there a posibility to use espeak oder play a ".wav" file with the robertalab?
It will be a cool feature :-)) especially for pupils.

**Comment by ensonic** [comment]
Yes, we're working on it:
https://github.com/OpenRoberta/robertalab/issues/425
