### ISSUE TITLE
robertalab failes on Debian Stretch

### ISSUE THREAD

**Issue by hashworks** [OpenRoberta/robertalab-ev3dev#49]
I'm using images that descend from the [ev3dev-stretch-ev3-generic](https://hub.docker.com/r/ev3dev/ev3dev-stretch-ev3-generic/tags/) docker builds on ev3 bricks.

When starting robertlab I get a `File not found` error since it tries to use `/dev/input/by-path/platform-gpio-keys.0-event`, which apperently got replaced by `/dev/input/by-path/platform-gpio_keys-event`.
Since both linked to `/dev/input/event0` I can simply add that file, but then I get another error:

```
INFO:roberta:--- starting ---
INFO:roberta.lab:python path: /usr/bin:/usr/lib/python35.zip:/usr/lib/python3.5:/usr/lib/python3.5/plat-arm-linux-gnueabi:/usr/lib/python3.5/lib-dynload:/usr/local/lib/python3.5/dist-packages:/usr/lib/python3/dist-packages

INFO:roberta.lab:status changed: disconnected
Traceback (most recent call last):
  File "/usr/bin/openrobertalab", line 41, in <module>
    main()
  File "/usr/bin/openrobertalab", line 36, in main
    service = Service('/org/openroberta/Lab1')
  File "/usr/lib/python3/dist-packages/roberta/lab.py", line 88, in __init__
    self.hal.clearDisplay()
  File "/usr/lib/python3/dist-packages/roberta/ev3.py", line 179, in clearDisplay
    self.lcd.update()
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 3135, in update
    self.mmap[:] = self._img.tobytes("raw", "1;IR")
IndexError: mmap slice assignment is wrong size
INFO:roberta:--- done ---
```

I asked @dlech about it who told me that `OpenRoberta/ev3dev-lang-python` hasn't been updated for stretch yet and redirected me here.

**Comment by ensonic** [comment]
Hi, @dlech probably redirected you to https://github.com/rhempel/ev3dev-lang-python/ since this needs to be ported to stretch first before I can port. For now you will need to use Jessie if you want to use open-roberta and/or python.

**Comment by hashworks** [comment]
Nah, he send me here :) But I'll open an issue there.

**Comment by ensonic** [comment]
@hashworks it is a known issue. We just released a ev3dev-lang-python-1.0 and will do the breaking changes afterwards.

**Comment by ensonic** [comment]
The image stuff needs more work since we support 2bit modes on stretch. I need to find a way to detect those.

**Comment by dlech** [comment]
Please try the 2017-11-01 ev3dev-stretch snapshot. There have been a number of fixes in ev3dev-lang-python. https://oss.jfrog.org/artifactory/list/oss-snapshot-local/org/ev3dev/brickstrap/

**Comment by hashworks** [comment]
Tested yesterday with 2017-11-01, works for me. Thanks!
