### ISSUE TITLE
received BT-message differs from sended one

### ISSUE THREAD

**Issue by afgym-baeu** [OpenRoberta/robertalab-ev3dev#51]
When sending the message
`Hello World!`
using a bluetooth connection, the receiving brick gets (or at least has a string containig)
`b'Hello World!'`
as a message. 

The additional characters do not depend on the string you send, it is always the prefix `b'`and the suffix `'`. 

I did not find any reason for that in [ev3.py]( robertalab-ev3dev/roberta/ev3.py ).

My programs for testing this issue are [here](https://gist.github.com/aBrAEUMER/04a6547e753ad775840606e6380a35cb).

**Comment by ensonic** [comment]
Ohh, that's related to switching to python 3.
