### ISSUE TITLE
Keyboard for wifi password entry has odd behaviors

### ISSUE THREAD

**Issue by lotu** [OpenRoberta/robertalab-ev3dev#59]
When entering the wifi password the key board is a "video game style" keyboard where you use the arrows to move your selector.  However some keys on the second from the top row skip over the top row and go directly to the text box, instead of going to the top row.

Reproduce:
Go to Wireless > select network with password > connect > textbox

1 go to 't' then push up arrow.  The text box is selected, when the '123' box should be selected.
if you go to the 'y' key and push up the '123' box is selected.  This problem happens for 'e' 'q' and 't' keys.

**Comment by ensonic** [comment]
Thanks for the feedback, could you please refile this for ev3dev as this is what provides the on-screen-keyboard:
https://github.com/ev3dev/ev3dev/issues

Also, FYI: you can mount the sd-card under a linux computer and create a connman config under /var/lib/connman to avoid the typing :)
