### ISSUE TITLE
Say block causes causes program to fail when run on ev3 dev

### ISSUE THREAD

**Issue by lotu** [OpenRoberta/robertalab-ev3dev#61]
In brickman v0.8.1 any program that includes the "say" block will simply crash instead of running when using ev3-dev.  The block works fine in the simulator.  I tested programs that have just a say block and programs that have wait blocks and logic before the say block.  Both immediately crash on startup when run.  No failure info is outputted on the ev3dev screen that I could capture.  

This is very bad because having a programing block that crashes the program is very confusing to students who are learning to program.

**Comment by boonto** [comment]
Do you have the newest version of robertalab-ev3dev? I just tested all the say related blocks and they work fine.

**Comment by ensonic** [comment]
@lotu could you answer the question? I am working on automatic version updates for one of the next releases to make sure this is handled transparently.

**Comment by lotu** [comment]
I believe I have the version from September.  I will be able to check next wensday.

**Comment by ensonic** [comment]
@lotu the support for the say block was recently added. I know it is not great to fail this way, sorry for that.

**Comment by lotu** [comment]
It's alright I totally understand how hard software development is.  :).  I actually didn't get a chance to test it today so I'll try to remember next week.

**Comment by lotu** [comment]
Sorry I won't have access to my robots today due to snow.  I will check back next week.

**Comment by lotu** [comment]
Okay checked today.  The say block still causes a failure.  
The version in the about page says brick man v0.8.1
Sys info: kernel 4.4.87-22-ev3dev-ev3
Model: LEGO MINDSTORMS EV3 Programable Brick
Revision: 0006

I was unable to find any other version numbers but I have a brick on me to test right now if you want me to.

**Comment by ensonic** [comment]
The output of `apt-cache show openrobertalab` would be useful. Did you ever run 'apt-get update && apt-get upgrade' on the brick? If not that is how to get the latest updates between full image releases. Unfortunately that is slow and not something for the regular user to run.

[Here](https://github.com/OpenRoberta/robertalab-ev3dev/issues/19) are some more complicated commands that let you update the single package.

**Comment by lotu** [comment]
Okay before updating: open roberta Version: 1.7.2+1.0.0
After: Version: 1.7.4+1.0.0

After updating it no longer crashes!

**Comment by ensonic** [comment]
Nice. Any sorry for the confusion. If I ever get to redo the API, I'll do all args as kwargs and/or add a version check into the code. But maybe the auto-update will save us here too.
