### ISSUE TITLE
connection to robot works but nothing happens when clicking play

### ISSUE THREAD

**Issue by oroulet** [OpenRoberta/robertalab-ev3dev#7]
Hi,

I installed ev3dev, updated all packaged and now brickman has a open robert lab option.
then I made a deb packaged from your rep and installed it on ev3dev
the systemd service refused to start but if running openroberta from shell it seems brickman is happy and connects and gives me a code.
Then I go to http://lab.open-roberta.org/# connect to robot with code, everything looks good. Then I write a simple program (drive forward for example) and click play. But clicking on play does not seem to do anything. nothing on the shell in ev3dev from openroberta script either. nothing interresting in lab.open-roberta.org log either.

clicking on show code shows some java code. Is there a way to see python code (I understood openroberta is supposed to send python code in this case.

am I missing something to make it work?
Thanks
Olivier
(I can make python scripts on ev3dev and run robot so that works, ut I would like to use open roberta for the kids)

**Comment by dlech** [comment]
We've just released a new ev3dev image file. It ships with a working version.

Please read http://www.ev3dev.org/news/2015/12/30/ev3dev-jessie-2015-12-30-release/

**Comment by ensonic** [comment]
Sorry, I missed the issue. @oroulet could you retry? FYI - the service write status information into journal, you can run:

```
sudo journalctl -f -u openrobertalab
```

to see it. If it still is not working, please attach the last ~20 lines here.

**Comment by oroulet** [comment]
It is working now! Thanks! The generated python code has issues by this is
something else

**Comment by ensonic** [comment]
@oroulet - thanks for testing again. Please file new tickets for the generated python code. I am working on several fixes already and will release an update soon.

**Comment by oroulet** [comment]
where can I follow your changes? Especially I had issue with generated
loops that were missing some kind of sleep() and where using up all cpu
thus prevent some events to be executed.

**Comment by ensonic** [comment]
This repo:
https://github.com/OpenRoberta/robertalab-ev3dev/commits/develop

no fix wrt to loop, so I am definitely interested in this one. FYI, the generated code is under /home/robot on your ev3.
