### ISSUE TITLE
Random number generation broken

### ISSUE THREAD

**Issue by timn** [OpenRoberta/robertalab-ev3dev#76]
When using the blocks "random integer" or "random fraction", execution fails with _randInt() or _randDouble() not found (Python KeyError). The generated code calls those functions without importing them from anywhere it seems.

**Comment by ensonic** [comment]
hmm for me this works.
![image](https://user-images.githubusercontent.com/1279486/101880959-06c98200-3b94-11eb-8089-08892341876c.png)
