### ISSUE TITLE
10 mins to start code!

### ISSUE THREAD

**Issue by snaildos** [OpenRoberta/robertalab-ev3dev#79]
Color detection and moving robots, take's 10 mins to start. How can I minimize the startup time??

**Comment by ensonic** [comment]
Please share your program (e.g. export from the filemenu and attach the xml file here or if the program is short simply take a screenshot). Programstartup is only a few seconds, definitely less then 10 sec, so there is something wrong.
Please also let us know if you use any non standard environment (like unsupported evdev version, own modifications etc.)

**Comment by snaildos** [comment]
Resolved. Adding a startup.py fixed the problems.
